config/routes.rb
Rails.application.routes.draw do
  post 'replace_pdf', to: 'pdf#replace'
  get 'search_pdf', to: 'pdf#search'
  root to: 'pdf#search'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/pdf.rb
class Pdf < ApplicationRecord

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :permit_file_upload

  private

  def permit_file_upload
    params.permit(:pdf_path) if request.post?
  end
end

app/controllers/pdf_controller.rb
class PdfController < ApplicationController
  begin
    # renderiza a página de pesquisa de PDF
    def search
    end

    def replace
      # Cria um novo objeto PDF::Reader a partir do caminho do arquivo PDF
      pdf = PDF::Reader.new(params(:pdf_path))
      # Lê o texto de cada página do PDF
      contents = pdf.pages.map { |page| page.text }.join
      #  Substitui do termo de busca
      replaced_contents = contents.gsub(params(:search_term), params(:replacement_term))
      # Define o caminho para o novo arquivo PDF que será gerado
      new_pdf_path = "#{Rails.root}/tmp/#{SecureRandom.uuid}.pdf"
      # Cria um novo objeto que representa o novo arquivo PDF
      Prawn::Document.generate(new_pdf_path) do
        text replaced_contents
      end
      # Aqui o novo arquivo PDF é enviado como resposta para o navegador do usuário
      send_file new_pdf_path, filename: 'resultado.pdf', type: 'application/pdf', disposition: 'attachment'
      flash[:notice] = 'Arquivo gerado com sucesso!'
    rescue => e
      flash[:alert] = "Houve um erro ao gerar o arquivo: #{e.message}"
      redirect_to root_path
    end
  end

  private

  def pdf_params
    params.require(:pdf).permit(:pdf_path, :search_term, :replacement_term)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pdf_helper.rb
module PdfHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SeekAndReplace</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pdf/replace.html.erb
<h1>Pdf#replace</h1>
<p>Find me in app/views/pdf/replace.html.erb</p>

app/views/pdf/search.html.erb
<h1>Buscar e substituir em PDF</h1>

<%= form_tag replace_pdf_path, method: :post, multipart: true do %>
  <p>
    <%= label_tag :pdf_path, "Arquivo PDF:" %>
    <%= file_field_tag :pdf_path %>
  </p>

  <p>
    <%= label_tag :search_term, "Buscar por:" %>
    <%= text_field_tag :search_term %>
  </p>

  <p>
    <%= label_tag :replacement_term, "Substituir por:" %>
    <%= text_field_tag :replacement_term %>
  </p>

  <p>
    <%= submit_tag "Buscar e substituir" %>
  </p>
<% end %>